version: '3.8'

services:
  # api:
  #   container_name: locathlete_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - ${PORT}:${PORT}
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  db:
    container_name: locathlete_db
    image: postgres:14.1
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}