// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"locathlete-server/ent/athleteschool"
	"locathlete-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// AthleteSchoolDelete is the builder for deleting a AthleteSchool entity.
type AthleteSchoolDelete struct {
	config
	hooks    []Hook
	mutation *AthleteSchoolMutation
}

// Where appends a list predicates to the AthleteSchoolDelete builder.
func (asd *AthleteSchoolDelete) Where(ps ...predicate.AthleteSchool) *AthleteSchoolDelete {
	asd.mutation.Where(ps...)
	return asd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (asd *AthleteSchoolDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(asd.hooks) == 0 {
		affected, err = asd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AthleteSchoolMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			asd.mutation = mutation
			affected, err = asd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(asd.hooks) - 1; i >= 0; i-- {
			if asd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = asd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, asd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (asd *AthleteSchoolDelete) ExecX(ctx context.Context) int {
	n, err := asd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (asd *AthleteSchoolDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: athleteschool.Table,
		},
	}
	if ps := asd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, asd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// AthleteSchoolDeleteOne is the builder for deleting a single AthleteSchool entity.
type AthleteSchoolDeleteOne struct {
	asd *AthleteSchoolDelete
}

// Exec executes the deletion query.
func (asdo *AthleteSchoolDeleteOne) Exec(ctx context.Context) error {
	n, err := asdo.asd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{athleteschool.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (asdo *AthleteSchoolDeleteOne) ExecX(ctx context.Context) {
	asdo.asd.ExecX(ctx)
}
