// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"locathlete-server/ent/migrate"

	"locathlete-server/ent/athlete"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Athlete is the client for interacting with the Athlete builders.
	Athlete *AthleteClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Athlete = NewAthleteClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Athlete: NewAthleteClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Athlete: NewAthleteClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Athlete.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Athlete.Use(hooks...)
}

// AthleteClient is a client for the Athlete schema.
type AthleteClient struct {
	config
}

// NewAthleteClient returns a client for the Athlete from the given config.
func NewAthleteClient(c config) *AthleteClient {
	return &AthleteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `athlete.Hooks(f(g(h())))`.
func (c *AthleteClient) Use(hooks ...Hook) {
	c.hooks.Athlete = append(c.hooks.Athlete, hooks...)
}

// Create returns a builder for creating a Athlete entity.
func (c *AthleteClient) Create() *AthleteCreate {
	mutation := newAthleteMutation(c.config, OpCreate)
	return &AthleteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Athlete entities.
func (c *AthleteClient) CreateBulk(builders ...*AthleteCreate) *AthleteCreateBulk {
	return &AthleteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Athlete.
func (c *AthleteClient) Update() *AthleteUpdate {
	mutation := newAthleteMutation(c.config, OpUpdate)
	return &AthleteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AthleteClient) UpdateOne(a *Athlete) *AthleteUpdateOne {
	mutation := newAthleteMutation(c.config, OpUpdateOne, withAthlete(a))
	return &AthleteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AthleteClient) UpdateOneID(id int) *AthleteUpdateOne {
	mutation := newAthleteMutation(c.config, OpUpdateOne, withAthleteID(id))
	return &AthleteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Athlete.
func (c *AthleteClient) Delete() *AthleteDelete {
	mutation := newAthleteMutation(c.config, OpDelete)
	return &AthleteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AthleteClient) DeleteOne(a *Athlete) *AthleteDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *AthleteClient) DeleteOneID(id int) *AthleteDeleteOne {
	builder := c.Delete().Where(athlete.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AthleteDeleteOne{builder}
}

// Query returns a query builder for Athlete.
func (c *AthleteClient) Query() *AthleteQuery {
	return &AthleteQuery{
		config: c.config,
	}
}

// Get returns a Athlete entity by its id.
func (c *AthleteClient) Get(ctx context.Context, id int) (*Athlete, error) {
	return c.Query().Where(athlete.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AthleteClient) GetX(ctx context.Context, id int) *Athlete {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AthleteClient) Hooks() []Hook {
	return c.hooks.Athlete
}
