// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"locathlete-server/ent/athlete"
	"locathlete-server/ent/athleteschool"
	"locathlete-server/ent/predicate"
	"locathlete-server/ent/school"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchoolQuery is the builder for querying School entities.
type SchoolQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.School
	// eager-loading edges.
	withAthletes       *AthleteQuery
	withSchoolAthletes *AthleteSchoolQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SchoolQuery builder.
func (sq *SchoolQuery) Where(ps ...predicate.School) *SchoolQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit adds a limit step to the query.
func (sq *SchoolQuery) Limit(limit int) *SchoolQuery {
	sq.limit = &limit
	return sq
}

// Offset adds an offset step to the query.
func (sq *SchoolQuery) Offset(offset int) *SchoolQuery {
	sq.offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SchoolQuery) Unique(unique bool) *SchoolQuery {
	sq.unique = &unique
	return sq
}

// Order adds an order step to the query.
func (sq *SchoolQuery) Order(o ...OrderFunc) *SchoolQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryAthletes chains the current query on the "athletes" edge.
func (sq *SchoolQuery) QueryAthletes() *AthleteQuery {
	query := &AthleteQuery{config: sq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(school.Table, school.FieldID, selector),
			sqlgraph.To(athlete.Table, athlete.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, school.AthletesTable, school.AthletesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySchoolAthletes chains the current query on the "school_athletes" edge.
func (sq *SchoolQuery) QuerySchoolAthletes() *AthleteSchoolQuery {
	query := &AthleteSchoolQuery{config: sq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(school.Table, school.FieldID, selector),
			sqlgraph.To(athleteschool.Table, athleteschool.SchoolColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, school.SchoolAthletesTable, school.SchoolAthletesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first School entity from the query.
// Returns a *NotFoundError when no School was found.
func (sq *SchoolQuery) First(ctx context.Context) (*School, error) {
	nodes, err := sq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{school.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SchoolQuery) FirstX(ctx context.Context) *School {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first School ID from the query.
// Returns a *NotFoundError when no School ID was found.
func (sq *SchoolQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{school.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SchoolQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single School entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one School entity is found.
// Returns a *NotFoundError when no School entities are found.
func (sq *SchoolQuery) Only(ctx context.Context) (*School, error) {
	nodes, err := sq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{school.Label}
	default:
		return nil, &NotSingularError{school.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SchoolQuery) OnlyX(ctx context.Context) *School {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only School ID in the query.
// Returns a *NotSingularError when more than one School ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SchoolQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{school.Label}
	default:
		err = &NotSingularError{school.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SchoolQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Schools.
func (sq *SchoolQuery) All(ctx context.Context) ([]*School, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sq *SchoolQuery) AllX(ctx context.Context) []*School {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of School IDs.
func (sq *SchoolQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := sq.Select(school.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SchoolQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SchoolQuery) Count(ctx context.Context) (int, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SchoolQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SchoolQuery) Exist(ctx context.Context) (bool, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SchoolQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SchoolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SchoolQuery) Clone() *SchoolQuery {
	if sq == nil {
		return nil
	}
	return &SchoolQuery{
		config:             sq.config,
		limit:              sq.limit,
		offset:             sq.offset,
		order:              append([]OrderFunc{}, sq.order...),
		predicates:         append([]predicate.School{}, sq.predicates...),
		withAthletes:       sq.withAthletes.Clone(),
		withSchoolAthletes: sq.withSchoolAthletes.Clone(),
		// clone intermediate query.
		sql:    sq.sql.Clone(),
		path:   sq.path,
		unique: sq.unique,
	}
}

// WithAthletes tells the query-builder to eager-load the nodes that are connected to
// the "athletes" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SchoolQuery) WithAthletes(opts ...func(*AthleteQuery)) *SchoolQuery {
	query := &AthleteQuery{config: sq.config}
	for _, opt := range opts {
		opt(query)
	}
	sq.withAthletes = query
	return sq
}

// WithSchoolAthletes tells the query-builder to eager-load the nodes that are connected to
// the "school_athletes" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SchoolQuery) WithSchoolAthletes(opts ...func(*AthleteSchoolQuery)) *SchoolQuery {
	query := &AthleteSchoolQuery{config: sq.config}
	for _, opt := range opts {
		opt(query)
	}
	sq.withSchoolAthletes = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.School.Query().
//		GroupBy(school.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SchoolQuery) GroupBy(field string, fields ...string) *SchoolGroupBy {
	grbuild := &SchoolGroupBy{config: sq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sq.sqlQuery(ctx), nil
	}
	grbuild.label = school.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.School.Query().
//		Select(school.FieldName).
//		Scan(ctx, &v)
func (sq *SchoolQuery) Select(fields ...string) *SchoolSelect {
	sq.fields = append(sq.fields, fields...)
	selbuild := &SchoolSelect{SchoolQuery: sq}
	selbuild.label = school.Label
	selbuild.flds, selbuild.scan = &sq.fields, selbuild.Scan
	return selbuild
}

func (sq *SchoolQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sq.fields {
		if !school.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SchoolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*School, error) {
	var (
		nodes       = []*School{}
		_spec       = sq.querySpec()
		loadedTypes = [2]bool{
			sq.withAthletes != nil,
			sq.withSchoolAthletes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*School).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &School{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := sq.withAthletes; query != nil {
		edgeids := make([]driver.Value, len(nodes))
		byid := make(map[int]*School)
		nids := make(map[int]map[*School]struct{})
		for i, node := range nodes {
			edgeids[i] = node.ID
			byid[node.ID] = node
			node.Edges.Athletes = []*Athlete{}
		}
		query.Where(func(s *sql.Selector) {
			joinT := sql.Table(school.AthletesTable)
			s.Join(joinT).On(s.C(athlete.FieldID), joinT.C(school.AthletesPrimaryKey[0]))
			s.Where(sql.InValues(joinT.C(school.AthletesPrimaryKey[1]), edgeids...))
			columns := s.SelectedColumns()
			s.Select(joinT.C(school.AthletesPrimaryKey[1]))
			s.AppendSelect(columns...)
			s.SetDistinct(false)
		})
		neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]interface{}, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]interface{}{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []interface{}) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*School]struct{}{byid[outValue]: struct{}{}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byid[outValue]] = struct{}{}
				return nil
			}
		})
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "athletes" node returned %v`, n.ID)
			}
			for kn := range nodes {
				kn.Edges.Athletes = append(kn.Edges.Athletes, n)
			}
		}
	}

	if query := sq.withSchoolAthletes; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*School)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.SchoolAthletes = []*AthleteSchool{}
		}
		query.Where(predicate.AthleteSchool(func(s *sql.Selector) {
			s.Where(sql.InValues(school.SchoolAthletesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.SchoolID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "school_id" returned %v for node %v`, fk, n)
			}
			node.Edges.SchoolAthletes = append(node.Edges.SchoolAthletes, n)
		}
	}

	return nodes, nil
}

func (sq *SchoolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.fields
	if len(sq.fields) > 0 {
		_spec.Unique = sq.unique != nil && *sq.unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SchoolQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sq *SchoolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   school.Table,
			Columns: school.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: school.FieldID,
			},
		},
		From:   sq.sql,
		Unique: true,
	}
	if unique := sq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, school.FieldID)
		for i := range fields {
			if fields[i] != school.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SchoolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(school.Table)
	columns := sq.fields
	if len(columns) == 0 {
		columns = school.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.unique != nil && *sq.unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SchoolGroupBy is the group-by builder for School entities.
type SchoolGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SchoolGroupBy) Aggregate(fns ...AggregateFunc) *SchoolGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sgb *SchoolGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sgb.path(ctx)
	if err != nil {
		return err
	}
	sgb.sql = query
	return sgb.sqlScan(ctx, v)
}

func (sgb *SchoolGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sgb.fields {
		if !school.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sgb *SchoolGroupBy) sqlQuery() *sql.Selector {
	selector := sgb.sql.Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sgb.fields)+len(sgb.fns))
		for _, f := range sgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sgb.fields...)...)
}

// SchoolSelect is the builder for selecting fields of School entities.
type SchoolSelect struct {
	*SchoolQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SchoolSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	ss.sql = ss.SchoolQuery.sqlQuery(ctx)
	return ss.sqlScan(ctx, v)
}

func (ss *SchoolSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ss.sql.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
